### ISSUE TITLE
Making a version that automatically removes all frames

### ISSUE THREAD

**Issue by imod-commission** [Naxdy/latency-slider-de#26]
hello, i tried this with the csk collection and it did work in matches and arena ui, only freezing in css. I am thinking if a version that have the frames removed by default and not requiring css menu, it could work without freezing the game if csk collection is present

**Comment by Naxdy** [comment]
Sounds like this is caused by the draw function then. If true, it would be as simple as removing [this line](https://github.com/Naxdy/latency-slider-de/blob/master/src/lib.rs#L231) from the code and recompiling. The CSS would then not show the current delay anymore, so you'd have to follow the instructions in [this comment](https://github.com/Naxdy/latency-slider-de/issues/24#issuecomment-2113132016) to set your delay, or go to an empty arena, where the delay would still be shown.

Can you try that and confirm whether this works for you?

**Comment by Naxdy** [comment]
FYI, if this is too much, there's also [this possible workaround](https://github.com/Naxdy/latency-slider-de/issues/22#issuecomment-1998080830)

**Comment by imod-commission** [comment]
Removing that line is still unusable but gives me a different outcome: originally it will freeze the entire game, and joycons vibrating forever. now it kills the bgm and cannot move in the css, but did not freeze the game.

However, also removing update_css_hook, display_css_hook seems to work; i set the frames in an arena then play a quickplay match and both 0 frames and 25 frames worked as expected

**Comment by imod-commission** [comment]
it also no longer conflicts with training mod, originally used to cause a panic and not able to boot, now both can work together

**Comment by Naxdy** [comment]
Thx for the info. If I ever get around to packaging the skyline toolchain in nix, I'll go ahead and add a separate "no UI in CSS" version to the releases.
