### ISSUE TITLE
Incompatibility with the Training mod

### ISSUE THREAD

**Issue by avahe-kellenberger** [Naxdy/latency-slider-de#31]
The [training mod](https://github.com/jugeeya/UltimateTrainingModpack) crashes when used in conjunction with this mod.

I assume it could very well be an issue with that mod, but am unsure.
It complains about not finding the draw function.

When I try to load this mod before that mod (by renaming the latency .nro file to be later in the alphabet), this mod fails to load.

This was an issue in the past as well, but was resolved previously with the renaming "hack" I mentioned above.

---

If you'd like any more specific details, please let me know. Thanks

---

Loading the mods without renaming:

![image](https://github.com/user-attachments/assets/24e20858-5a29-463f-ab24-b890634e3381)

Loading the mods when I've renamed `liblatency_slider_de.nro -> libzlatency_slider_de.nro`:

![image](https://github.com/user-attachments/assets/f3cd5853-7042-4efa-ba22-1209fe884c72)

**Comment by Naxdy** [comment]
Figured this would probably be an issue.

The problem here is that both the training modpack and `latency-slider-de` hook the game's draw function, and they do so by trying to find its signature (see https://github.com/Naxdy/latency-slider-de/blob/master/src/offsets.rs#L85-L94 ).

Problem is, once one of the mods hooks the function, the signature changes, so whichever mod is loaded second will fail to find it.

For now, I suggest enabling / disabling the individual mods as you need them, until I figure out a better way to deal with both training mode modpack and latency slider DE in the same install.

**Comment by Naxdy** [comment]
Also love the error codes we both chose in our mods :)
